### ISSUE TITLE
KeyError if input text size greater than around 400 chars 

### ISSUE THREAD

**Issue by mayank10j** [notAI-tech/fastPunct#10]
fastPunct punctation fails following quoted error if input text size is greater than around 400 chars. 
To replicate run fastPunct.punct method with any input text string with more than 400 chars. 

> 
> input_text_len 407
> File "/opt/conda/lib/python3.7/site-packages/fastpunct/fastpunct.py", line 175, in punct
>     return decode(self.model, self.parameters, input_texts, self.allowed_extras, batch_size)
>   File "/opt/conda/lib/python3.7/site-packages/fastpunct/fastpunct.py", line 119, in decode
>     outputs = [out_dict[text] for text in input_texts_c]
>   File "/opt/conda/lib/python3.7/site-packages/fastpunct/fastpunct.py", line 119, in <listcomp>
>     outputs = [out_dict[text] for text in input_texts_c]
> KeyError: "lorem ipsum is simply dummy text of the printing and typesetting industry. lorem ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. it has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. it was popularised in the dkdd may be dd"

**Comment by harikodali** [comment]
Max input length supported is 400 characters
