### ISSUE TITLE
Why a Seq2Seq instead of Classification Network?

### ISSUE THREAD

**Issue by erksch** [notAI-tech/fastPunct#12]
Hey there!

I started reading about text correction with Deep Learning and most certainly read all your blog posts.

But I still wonder why you would choose a Seq2Seq network for punctuation restoration over a classification network that classifies for each token if it should be followed by some sort of punctuation. For a Seq2Seq model, you have to make sure the network does not change anything but the punctuation in the sequence, in a classification network you get this out of the box. 

Does a Seq2Seq model perform better or is this easier to train for this purpose? If so, could you elaborate on why? 
Or is this maybe part of a greater goal to do punctuation restoration, spelling, and grammar correction with one large Seq2Seq network?

Also, what is your network input, as far as I can tell you are not using word embeddings? I guess this is why your model checkpoint is so small.

**Comment by erksch** [comment]
Hey would be nice to get an answer on this :)

**Comment by erksch** [comment]
@harikodali @bedapudi6788 could you shed some light?

**Comment by harikodali** [comment]
hi @erksch , you're right in that a classification model is better suited for this problem, seq2seq model will have the issue of unwanted changes. No particular reason as such for choosing seq2seq, at that time it was the idea we have, in the next update(not sure when) it will be a classification model.

**Comment by erksch** [comment]
Okay great! And what are you using regarding your input? (word embeddings, one hot character vectors)

**Comment by bedapudi6788** [comment]
@erksch we have moved to experimenting with punct + simple (and comples in future) spell correction in the same model (by finetuning lms). Also, we realized that for adding support for multiple types of punctuation, stacking of multiple classification networks is required. For exaple. if we want the output to include " and capitalisation, 2 classifications are required per word/ token.
