### ISSUE TITLE
missing hyphen

### ISSUE THREAD

**Issue by tsunehiko** [notAI-tech/fastPunct#14]
If the input contains a hyphen, the hyphen is missing from the output. I want to keep the hyphen in the output as well. How can I do this?

exmaple
Input
Last week it was the return of the world's longest flight -- Singapore to New York JFK. This week comes another new aviation record: the world's longest flight in a single-aisle aircraft. Air Transat flight TS690 flew transatlantic from Montreal, Canada, to Athens, Greece, on Monday -- a journey of 7,600 kilometers, or 4,754 miles. So far, so normal -- except the eight-hour, 32-minute flight was performed in a narrowbody Airbus A321neoLR.
Output
Last week it was the return of the world's longest flight  Singapore to New York JFK this week comes another new aviation record: the world's longest flight in a Singleaisle aircraft air Transat flight TS690 flew transatlantic from Montreal Canada to Athens Greece on Monday  a journey of 7,600 kilometers, or 475.4 miles so far. So normal  Except the Eighthour 32Minute flight was performed in a Narrowbody Airbus A321neolR.

**Comment by harikodali** [comment]
possibly hyphens have been removed when cleaning the training data, so they're not in vocab and ignored. Unless we re-train the whole model, this issue can't be solved.
Will keep this in mind and try to support it for next model release.
