### ISSUE TITLE
Model Input

### ISSUE THREAD

**Issue by nikitaame** [notAI-tech/fastPunct#15]
Hi!

Thank you so much for the model. I am trying to use it for a project on iOS. I have successfully converted it using CoreMLTools but now I am trying to use it. Would you please be so kind as to provide documentation on the expected input of the model? After conversion I see:

<img width="428" alt="Screen Shot 2020-11-11 at 10 47 34 PM" src="https://user-images.githubusercontent.com/6069972/98905231-ebbe0200-246f-11eb-8009-dbdf9cf9f89f.png">

The only things I had done was add:

```
import coremltools
import tensorflow as tf
```
and
```
mlmodel = coremltools.convert(self.model)
mlmodel.save('punctuation.mlmodel')
```
(to the init)  

It would be nice if in future iterations, the input/output could be a little more straightforward.

Thanks!

**Comment by nikitaame** [comment]
Could a lot of the steps you do in `decode` be moved to occur within the model perhaps?

**Comment by nikitaame** [comment]
@harikodali any thoughts on these suggestions?

**Comment by bedapudi6788** [comment]
please refer to huggingface t5 documentation. the repo now uses huggingface transformers.

**Comment by nikitaame** [comment]
Sorry @bedapudi6788 but it isn't helpful to say "go do this" and close an issue. If you have a suggested resolution, please provide direct links or an actual suggestion.
