### ISSUE TITLE
The proportion for "!" is extremely high

### ISSUE THREAD

**Issue by xixiaohan** [notAI-tech/fastPunct#19]

**Comment by levidehaan** [comment]
This is also true for me.
Is there any way to limit the output to periods and commas?
If it requires retraining a model is there a possiblitily that you would push up your training data so it could be modified to only learn periods and commas and no other punctuation?
I'd be cool with pushing a new periods/commas only model back as a pull request for others who want to use it.

**Comment by bedapudi6788** [comment]
@xixiaohan @levidehaan we released an updated model. please check and re-open if issue persists.
