### ISSUE TITLE
How to increase indices sequence length?

### ISSUE THREAD

**Issue by bekmuradov** [notAI-tech/fastPunct#28]
Hi. I am trying to restore punctuation on auto generated transcript and I see this in the console:

**Token indices sequence length is longer than the specified maximum sequence length for this model (998 > 512). Running this sequence through the model will result in indexing errors**

Is it possible to increase the limit?

**Comment by harikodali** [comment]
This is warning from tokenizer which has max_len attribute set to 512 by default, you can ignore this. model will work fine on any sequence length.
