### ISSUE TITLE
Format of training dataset

### ISSUE THREAD

**Issue by gaurav0804** [notAI-tech/fastPunct#4]
What is the format of training data set. It will help in fine tuning the model with contextual data

**Comment by fengdanhuang** [comment]
agree with @gaurav0804! The format of training data set will help a lot with contextual data. Besides, @harikodali Could you provide model training code too in the github so we can try the model training part. That will be great!

**Comment by hari-krishna-k** [comment]
Will add the training code and data format in 1-2 weeks

**Comment by fengdanhuang** [comment]
@harikodali How is the training data and training code so far? Are you going to add soon?

**Comment by erksch** [comment]
Also very interested in this!

**Comment by bedapudi6788** [comment]
@gaurav0804 @erksch @fengdanhuang the repo now uses huggingface transformers. Please refer to their documentation.
