### ISSUE TITLE
Data loss: not an sstable (bad magic number)

### ISSUE THREAD

**Issue by softguy** [notAI-tech/fastPunct#5]
Thanks for this great app. However, when I started to use it, I got the following error
...\.fastPunct_en\checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

Tried both tensorflow 1.12 and tf 2. 
Does it mean that u may need to reupload the checkpoint file?

Thanks.

**Comment by sergey-drpa** [comment]
The same issue!

**Comment by bedapudi6788** [comment]
```rm -rf ~/.fastPunct_en/``` 

this will delete the locally cached checkpoint and will re-download the data.

**Comment by softguy** [comment]
Thanks, just tried. but still same error:

2020-06-27 23:53:21.661513: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ...\.fastPunct_en\checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

Checked the downloaded file:
https://github.com/notAI-tech/fastPunct/releases/download/checkpoint-release/fastpunct_eng_weights.h5
(renamed to checkpoint after downloaded to ~/.fastPunct_en
seems the same as the one causing problem before:

06/24/2020  12:20 PM         2,408,928 fastpunct_eng_weights.h5
md5 is:
328EC2DD3C3DFCD8312B62AAFA3CEFDC  fastpunct_eng_weights.h5

06/27/2020  11:53 PM         2,408,928 checkpoint
md5 is:
328EC2DD3C3DFCD8312B62AAFA3CEFDC  \Users\a\.fastPunct_en\checkpoint

Do you mind upload the right checkpoint  file? Thanks.......

**Comment by bedapudi6788** [comment]
This is weird. I am unable to reproduce the issue. Must be due to some specific library versions.

https://colab.research.google.com/drive/1RAGzGX-awCGzfr0vFDJqevqQUIPQtGOi?usp=sharing Tested just now on this colab.

**Comment by gvskalyan** [comment]
@bedapudi6788 I am also getting the same error. Can you please check this.

**Comment by bedapudi6788** [comment]
paging the author @harikodali

**Comment by harikodali** [comment]
This issue is not reproducible from our end, please share your full environment details with version info for individual libraries

**Comment by gvskalyan** [comment]
Hi, Please find the conda's environment.yml attached (as environment.txt)

[environment.txt](https://github.com/notAI-tech/fastPunct/files/4868873/environment.txt)

**Comment by harikodali** [comment]
Update to the latest version using pip install --upgrade fastpunct and see if it solves your problem.

**Comment by gvskalyan** [comment]
Thanks, It fixed the issue.
The time taken to run the example [here](https://github.com/notAI-tech/fastPunct/blob/develop/README.md#usage), excluding the model load time is around 7 seconds on CPU, though the prediction is char based, it would be better if time can be reduced.

**Comment by softguy** [comment]
Fixed, Thanks, seems to be file name extension issue. -- tensorflow requires .h5 and .pkl in the filename?
