### ISSUE TITLE
Provide Frozen Model

### ISSUE THREAD

**Issue by nikitaame** [notAI-tech/fastPunct#8]
Hi! I am hoping to use this in an iOS project. Could you convert the model to CoreML or at least provide the frozen model (.pb file)? Thanks

**Comment by harikodali** [comment]
Model architecture is already there in code, build a model instance, load saved weights, save the full model. If you want .pb file look into this [https://www.dlology.com/blog/how-to-convert-trained-keras-model-to-tensorflow-and-make-prediction/](url)

**Comment by nikitaame** [comment]
<img width="415" alt="Screen Shot 2020-08-19 at 4 59 27 PM" src="https://user-images.githubusercontent.com/6069972/90701832-8a0a4500-e23e-11ea-9c21-b7a596ccbace.png">

Thank you for that link @harikodali 

As a first step, I was trying to save the model as h5 using `self.model.save('punctuation.h5')` and then open it with Netron and I was getting the above error. Was also getting that error when trying to convert the h5 model into coreml. Are you able to save and open using Netron?
